# fly.toml app configuration file generated for hary-bot on 2023-08-01T23:04:06+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hary-bot"
primary_region = "arn"

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
