/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationHarysDataItemAttributesConversationDataAttributesMessagesDataItemAttributesCreatedBy } from './conversationHarysDataItemAttributesConversationDataAttributesMessagesDataItemAttributesCreatedBy';
import type { ConversationHarysDataItemAttributesConversationDataAttributesMessagesDataItemAttributesUpdatedBy } from './conversationHarysDataItemAttributesConversationDataAttributesMessagesDataItemAttributesUpdatedBy';

export type ConversationHarysDataItemAttributesConversationDataAttributesMessagesDataItemAttributes = {
  contentReceiver?: string;
  contentSender?: string;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: ConversationHarysDataItemAttributesConversationDataAttributesMessagesDataItemAttributesCreatedBy;
  updatedBy?: ConversationHarysDataItemAttributesConversationDataAttributesMessagesDataItemAttributesUpdatedBy;
};
