/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationHarysDataItemAttributesConversationDataAttributesHarys } from './conversationHarysDataItemAttributesConversationDataAttributesHarys';
import type { ConversationHarysDataItemAttributesConversationDataAttributesMessages } from './conversationHarysDataItemAttributesConversationDataAttributesMessages';
import type { ConversationHarysDataItemAttributesConversationDataAttributesCreatedBy } from './conversationHarysDataItemAttributesConversationDataAttributesCreatedBy';
import type { ConversationHarysDataItemAttributesConversationDataAttributesUpdatedBy } from './conversationHarysDataItemAttributesConversationDataAttributesUpdatedBy';

export type ConversationHarysDataItemAttributesConversationDataAttributes = {
  harys?: ConversationHarysDataItemAttributesConversationDataAttributesHarys;
  messages?: ConversationHarysDataItemAttributesConversationDataAttributesMessages;
  publicKey?: string;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: ConversationHarysDataItemAttributesConversationDataAttributesCreatedBy;
  updatedBy?: ConversationHarysDataItemAttributesConversationDataAttributesUpdatedBy;
};
