/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationResponseDataObject } from './conversationResponseDataObject';
import type { ConversationResponseMeta } from './conversationResponseMeta';

export interface ConversationResponse {
  data?: ConversationResponseDataObject;
  meta?: ConversationResponseMeta;
}
