/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationHarys } from './conversationHarys';
import type { ConversationMessages } from './conversationMessages';
import type { ConversationCreatedBy } from './conversationCreatedBy';
import type { ConversationUpdatedBy } from './conversationUpdatedBy';

export interface Conversation {
  harys?: ConversationHarys;
  messages?: ConversationMessages;
  publicKey: string;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: ConversationCreatedBy;
  updatedBy?: ConversationUpdatedBy;
}
