/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationHarysDataItemAttributesAdminUser } from './conversationHarysDataItemAttributesAdminUser';
import type { ConversationHarysDataItemAttributesConversation } from './conversationHarysDataItemAttributesConversation';
import type { ConversationHarysDataItemAttributesCreatedBy } from './conversationHarysDataItemAttributesCreatedBy';
import type { ConversationHarysDataItemAttributesUpdatedBy } from './conversationHarysDataItemAttributesUpdatedBy';

export type ConversationHarysDataItemAttributes = {
  adminUser?: ConversationHarysDataItemAttributesAdminUser;
  publicKey?: string;
  conversation?: ConversationHarysDataItemAttributesConversation;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: ConversationHarysDataItemAttributesCreatedBy;
  updatedBy?: ConversationHarysDataItemAttributesUpdatedBy;
};
