/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationMessagesDataItemAttributesConversationDataAttributesHarys } from './conversationMessagesDataItemAttributesConversationDataAttributesHarys';
import type { ConversationMessagesDataItemAttributesConversationDataAttributesMessages } from './conversationMessagesDataItemAttributesConversationDataAttributesMessages';
import type { ConversationMessagesDataItemAttributesConversationDataAttributesCreatedBy } from './conversationMessagesDataItemAttributesConversationDataAttributesCreatedBy';
import type { ConversationMessagesDataItemAttributesConversationDataAttributesUpdatedBy } from './conversationMessagesDataItemAttributesConversationDataAttributesUpdatedBy';

export type ConversationMessagesDataItemAttributesConversationDataAttributes = {
  harys?: ConversationMessagesDataItemAttributesConversationDataAttributesHarys;
  messages?: ConversationMessagesDataItemAttributesConversationDataAttributesMessages;
  publicKey?: string;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: ConversationMessagesDataItemAttributesConversationDataAttributesCreatedBy;
  updatedBy?: ConversationMessagesDataItemAttributesConversationDataAttributesUpdatedBy;
};
