/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationHarysDataItemAttributesAdminUserDataAttributesRoles } from './conversationHarysDataItemAttributesAdminUserDataAttributesRoles';
import type { ConversationHarysDataItemAttributesAdminUserDataAttributesCreatedBy } from './conversationHarysDataItemAttributesAdminUserDataAttributesCreatedBy';
import type { ConversationHarysDataItemAttributesAdminUserDataAttributesUpdatedBy } from './conversationHarysDataItemAttributesAdminUserDataAttributesUpdatedBy';

export type ConversationHarysDataItemAttributesAdminUserDataAttributes = {
  firstname?: string;
  lastname?: string;
  username?: string;
  email?: string;
  resetPasswordToken?: string;
  registrationToken?: string;
  isActive?: boolean;
  roles?: ConversationHarysDataItemAttributesAdminUserDataAttributesRoles;
  blocked?: boolean;
  preferedLanguage?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: ConversationHarysDataItemAttributesAdminUserDataAttributesCreatedBy;
  updatedBy?: ConversationHarysDataItemAttributesAdminUserDataAttributesUpdatedBy;
};
