/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationMessagesDataItemAttributesConversationDataAttributes } from './conversationMessagesDataItemAttributesConversationDataAttributes';

export type ConversationMessagesDataItemAttributesConversationData = {
  id?: number;
  attributes?: ConversationMessagesDataItemAttributesConversationDataAttributes;
};
