/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesUsers } from './conversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesUsers';
import type { ConversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesPermissions } from './conversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesPermissions';
import type { ConversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesCreatedBy } from './conversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesCreatedBy';
import type { ConversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesUpdatedBy } from './conversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesUpdatedBy';

export type ConversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributes = {
  name?: string;
  code?: string;
  description?: string;
  users?: ConversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesUsers;
  permissions?: ConversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesPermissions;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: ConversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesCreatedBy;
  updatedBy?: ConversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesUpdatedBy;
};
