/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRole } from './conversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRole';
import type { ConversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedBy } from './conversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedBy';
import type { ConversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedBy } from './conversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedBy';

export type ConversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesPermissionsDataItemAttributes = {
  action?: string;
  subject?: string;
  properties?: unknown;
  conditions?: unknown;
  role?: ConversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRole;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: ConversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedBy;
  updatedBy?: ConversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedBy;
};
