/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesUpdatedByData } from './conversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesUpdatedByData';

export type ConversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesUpdatedBy = {
  data?: ConversationHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesUpdatedByData;
};
