/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorDataOneOf } from './errorDataOneOf';
import type { ErrorDataOneOfTwoItem } from './errorDataOneOfTwoItem';

export type ErrorData = ErrorDataOneOf | ErrorDataOneOfTwoItem[] | null;
