/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { HaryListResponseDataItem } from './haryListResponseDataItem';
import type { HaryListResponseMeta } from './haryListResponseMeta';

export interface HaryListResponse {
  data?: HaryListResponseDataItem[];
  meta?: HaryListResponseMeta;
}
