/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { HaryConversationDataAttributesHarysDataItemAttributesAdminUser } from './haryConversationDataAttributesHarysDataItemAttributesAdminUser';
import type { HaryConversationDataAttributesHarysDataItemAttributesConversation } from './haryConversationDataAttributesHarysDataItemAttributesConversation';
import type { HaryConversationDataAttributesHarysDataItemAttributesCreatedBy } from './haryConversationDataAttributesHarysDataItemAttributesCreatedBy';
import type { HaryConversationDataAttributesHarysDataItemAttributesUpdatedBy } from './haryConversationDataAttributesHarysDataItemAttributesUpdatedBy';

export type HaryConversationDataAttributesHarysDataItemAttributes = {
  adminUser?: HaryConversationDataAttributesHarysDataItemAttributesAdminUser;
  publicKey?: string;
  conversation?: HaryConversationDataAttributesHarysDataItemAttributesConversation;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: HaryConversationDataAttributesHarysDataItemAttributesCreatedBy;
  updatedBy?: HaryConversationDataAttributesHarysDataItemAttributesUpdatedBy;
};
