/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { HaryAdminUser } from './haryAdminUser';
import type { HaryConversation } from './haryConversation';
import type { HaryCreatedBy } from './haryCreatedBy';
import type { HaryUpdatedBy } from './haryUpdatedBy';

export interface Hary {
  adminUser?: HaryAdminUser;
  publicKey?: string;
  conversation?: HaryConversation;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: HaryCreatedBy;
  updatedBy?: HaryUpdatedBy;
}
