/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { HaryAdminUserDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRole } from './haryAdminUserDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRole';
import type { HaryAdminUserDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedBy } from './haryAdminUserDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedBy';
import type { HaryAdminUserDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedBy } from './haryAdminUserDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedBy';

export type HaryAdminUserDataAttributesRolesDataItemAttributesPermissionsDataItemAttributes = {
  action?: string;
  subject?: string;
  properties?: unknown;
  conditions?: unknown;
  role?: HaryAdminUserDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRole;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: HaryAdminUserDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedBy;
  updatedBy?: HaryAdminUserDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedBy;
};
