/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { HaryConversationDataAttributesHarysDataItemAttributesConversationData } from './haryConversationDataAttributesHarysDataItemAttributesConversationData';

export type HaryConversationDataAttributesHarysDataItemAttributesConversation = {
  data?: HaryConversationDataAttributesHarysDataItemAttributesConversationData;
};
