/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { HaryAdminUserDataAttributesRoles } from './haryAdminUserDataAttributesRoles';
import type { HaryAdminUserDataAttributesCreatedBy } from './haryAdminUserDataAttributesCreatedBy';
import type { HaryAdminUserDataAttributesUpdatedBy } from './haryAdminUserDataAttributesUpdatedBy';

export type HaryAdminUserDataAttributes = {
  firstname?: string;
  lastname?: string;
  username?: string;
  email?: string;
  resetPasswordToken?: string;
  registrationToken?: string;
  isActive?: boolean;
  roles?: HaryAdminUserDataAttributesRoles;
  blocked?: boolean;
  preferedLanguage?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: HaryAdminUserDataAttributesCreatedBy;
  updatedBy?: HaryAdminUserDataAttributesUpdatedBy;
};
