/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { HaryAdminUserDataAttributesRolesDataItemAttributesUsers } from './haryAdminUserDataAttributesRolesDataItemAttributesUsers';
import type { HaryAdminUserDataAttributesRolesDataItemAttributesPermissions } from './haryAdminUserDataAttributesRolesDataItemAttributesPermissions';
import type { HaryAdminUserDataAttributesRolesDataItemAttributesCreatedBy } from './haryAdminUserDataAttributesRolesDataItemAttributesCreatedBy';
import type { HaryAdminUserDataAttributesRolesDataItemAttributesUpdatedBy } from './haryAdminUserDataAttributesRolesDataItemAttributesUpdatedBy';

export type HaryAdminUserDataAttributesRolesDataItemAttributes = {
  name?: string;
  code?: string;
  description?: string;
  users?: HaryAdminUserDataAttributesRolesDataItemAttributesUsers;
  permissions?: HaryAdminUserDataAttributesRolesDataItemAttributesPermissions;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: HaryAdminUserDataAttributesRolesDataItemAttributesCreatedBy;
  updatedBy?: HaryAdminUserDataAttributesRolesDataItemAttributesUpdatedBy;
};
