/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { HaryConversationDataAttributesMessagesDataItemAttributesCreatedBy } from './haryConversationDataAttributesMessagesDataItemAttributesCreatedBy';
import type { HaryConversationDataAttributesMessagesDataItemAttributesUpdatedBy } from './haryConversationDataAttributesMessagesDataItemAttributesUpdatedBy';

export type HaryConversationDataAttributesMessagesDataItemAttributes = {
  contentReceiver?: string;
  contentSender?: string;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: HaryConversationDataAttributesMessagesDataItemAttributesCreatedBy;
  updatedBy?: HaryConversationDataAttributesMessagesDataItemAttributesUpdatedBy;
};
