/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { HaryAdminUserDataAttributesCreatedByDataAttributes } from './haryAdminUserDataAttributesCreatedByDataAttributes';

export type HaryAdminUserDataAttributesCreatedByData = {
  id?: number;
  attributes?: HaryAdminUserDataAttributesCreatedByDataAttributes;
};
