/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { MessageConversationDataAttributesHarysDataItemAttributesAdminUserDataAttributesRoles } from './messageConversationDataAttributesHarysDataItemAttributesAdminUserDataAttributesRoles';
import type { MessageConversationDataAttributesHarysDataItemAttributesAdminUserDataAttributesCreatedBy } from './messageConversationDataAttributesHarysDataItemAttributesAdminUserDataAttributesCreatedBy';
import type { MessageConversationDataAttributesHarysDataItemAttributesAdminUserDataAttributesUpdatedBy } from './messageConversationDataAttributesHarysDataItemAttributesAdminUserDataAttributesUpdatedBy';

export type MessageConversationDataAttributesHarysDataItemAttributesAdminUserDataAttributes = {
  firstname?: string;
  lastname?: string;
  username?: string;
  email?: string;
  resetPasswordToken?: string;
  registrationToken?: string;
  isActive?: boolean;
  roles?: MessageConversationDataAttributesHarysDataItemAttributesAdminUserDataAttributesRoles;
  blocked?: boolean;
  preferedLanguage?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: MessageConversationDataAttributesHarysDataItemAttributesAdminUserDataAttributesCreatedBy;
  updatedBy?: MessageConversationDataAttributesHarysDataItemAttributesAdminUserDataAttributesUpdatedBy;
};
