/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { MessageCreatedByDataAttributesRolesDataItemAttributesUsers } from './messageCreatedByDataAttributesRolesDataItemAttributesUsers';
import type { MessageCreatedByDataAttributesRolesDataItemAttributesPermissions } from './messageCreatedByDataAttributesRolesDataItemAttributesPermissions';
import type { MessageCreatedByDataAttributesRolesDataItemAttributesCreatedBy } from './messageCreatedByDataAttributesRolesDataItemAttributesCreatedBy';
import type { MessageCreatedByDataAttributesRolesDataItemAttributesUpdatedBy } from './messageCreatedByDataAttributesRolesDataItemAttributesUpdatedBy';

export type MessageCreatedByDataAttributesRolesDataItemAttributes = {
  name?: string;
  code?: string;
  description?: string;
  users?: MessageCreatedByDataAttributesRolesDataItemAttributesUsers;
  permissions?: MessageCreatedByDataAttributesRolesDataItemAttributesPermissions;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: MessageCreatedByDataAttributesRolesDataItemAttributesCreatedBy;
  updatedBy?: MessageCreatedByDataAttributesRolesDataItemAttributesUpdatedBy;
};
