/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { MessageConversationDataAttributesHarys } from './messageConversationDataAttributesHarys';
import type { MessageConversationDataAttributesMessages } from './messageConversationDataAttributesMessages';
import type { MessageConversationDataAttributesCreatedBy } from './messageConversationDataAttributesCreatedBy';
import type { MessageConversationDataAttributesUpdatedBy } from './messageConversationDataAttributesUpdatedBy';

export type MessageConversationDataAttributes = {
  harys?: MessageConversationDataAttributesHarys;
  messages?: MessageConversationDataAttributesMessages;
  publicKey?: string;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: MessageConversationDataAttributesCreatedBy;
  updatedBy?: MessageConversationDataAttributesUpdatedBy;
};
