/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { MessageConversationDataAttributesHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesUpdatedByDataAttributes } from './messageConversationDataAttributesHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesUpdatedByDataAttributes';

export type MessageConversationDataAttributesHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesUpdatedByData = {
  id?: number;
  attributes?: MessageConversationDataAttributesHarysDataItemAttributesAdminUserDataAttributesRolesDataItemAttributesUpdatedByDataAttributes;
};
