/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { MessageResponseDataObject } from './messageResponseDataObject';
import type { MessageResponseMeta } from './messageResponseMeta';

export interface MessageResponse {
  data?: MessageResponseDataObject;
  meta?: MessageResponseMeta;
}
