/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { MessageConversationDataAttributesHarysDataItemAttributesAdminUserDataAttributes } from './messageConversationDataAttributesHarysDataItemAttributesAdminUserDataAttributes';

export type MessageConversationDataAttributesHarysDataItemAttributesAdminUserData = {
  id?: number;
  attributes?: MessageConversationDataAttributesHarysDataItemAttributesAdminUserDataAttributes;
};
