/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { MessageListResponseDataItem } from './messageListResponseDataItem';
import type { MessageListResponseMeta } from './messageListResponseMeta';

export interface MessageListResponse {
  data?: MessageListResponseDataItem[];
  meta?: MessageListResponseMeta;
}
