/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { MessageCreatedBy } from './messageCreatedBy';
import type { MessageUpdatedBy } from './messageUpdatedBy';

export interface Message {
  contentReceiver?: string;
  contentSender?: string;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: MessageCreatedBy;
  updatedBy?: MessageUpdatedBy;
}
