/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { MessageConversationDataAttributesMessagesDataItemAttributesConversation } from './messageConversationDataAttributesMessagesDataItemAttributesConversation';
import type { MessageConversationDataAttributesMessagesDataItemAttributesCreatedBy } from './messageConversationDataAttributesMessagesDataItemAttributesCreatedBy';
import type { MessageConversationDataAttributesMessagesDataItemAttributesUpdatedBy } from './messageConversationDataAttributesMessagesDataItemAttributesUpdatedBy';

export type MessageConversationDataAttributesMessagesDataItemAttributes = {
  conversation?: MessageConversationDataAttributesMessagesDataItemAttributesConversation;
  contentReceiver?: string;
  contentSender?: string;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: MessageConversationDataAttributesMessagesDataItemAttributesCreatedBy;
  updatedBy?: MessageConversationDataAttributesMessagesDataItemAttributesUpdatedBy;
};
