/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { MessageConversationDataAttributesHarysDataItemAttributesAdminUser } from './messageConversationDataAttributesHarysDataItemAttributesAdminUser';
import type { MessageConversationDataAttributesHarysDataItemAttributesCreatedBy } from './messageConversationDataAttributesHarysDataItemAttributesCreatedBy';
import type { MessageConversationDataAttributesHarysDataItemAttributesUpdatedBy } from './messageConversationDataAttributesHarysDataItemAttributesUpdatedBy';

export type MessageConversationDataAttributesHarysDataItemAttributes = {
  adminUser?: MessageConversationDataAttributesHarysDataItemAttributesAdminUser;
  publicKey?: string;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: MessageConversationDataAttributesHarysDataItemAttributesCreatedBy;
  updatedBy?: MessageConversationDataAttributesHarysDataItemAttributesUpdatedBy;
};
