/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { MessageCreatedByDataAttributesRoles } from './messageCreatedByDataAttributesRoles';
import type { MessageCreatedByDataAttributesCreatedBy } from './messageCreatedByDataAttributesCreatedBy';
import type { MessageCreatedByDataAttributesUpdatedBy } from './messageCreatedByDataAttributesUpdatedBy';

export type MessageCreatedByDataAttributes = {
  firstname?: string;
  lastname?: string;
  username?: string;
  email?: string;
  resetPasswordToken?: string;
  registrationToken?: string;
  isActive?: boolean;
  roles?: MessageCreatedByDataAttributesRoles;
  blocked?: boolean;
  preferedLanguage?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: MessageCreatedByDataAttributesCreatedBy;
  updatedBy?: MessageCreatedByDataAttributesUpdatedBy;
};
