/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

/**
 * every controller of the api
 */
export type UsersPermissionsPermissionsTreeControllers = {[key: string]: {[key: string]: {
  enabled?: boolean;
  policy?: string;
}}};
